---

# Dependencies
- name: "{{ app_name }}-deps_apt"
  apt: pkg={{ item }} state=installed
  with_items:
    - python-virtualenv
    - python-pip
    - supervisor

# Pre-install
- name: "{{ app_name }}-preinst_stop_supervisor"
  shell: service supervisor stop

- name: "{{ app_name }}-preinst_installer_dirs"
  file: path={{ item }} state=directory owner=www-data group=www-data
  with_items:
    - "{{ prefix }}"
    - "{{ tmp_path }}"

- name: "{{ app_name }}-preinst_installer_upload"
  copy: src={{ item }} dest={{ tmp_path }} owner=www-data group=www-data
  with_items:
    - "{{ installer_tgz }}"

- name: "{{ app_name }}-preinst_installer_untar"
  shell: cd {{ tmp_path }} && tar zxf {{ installer_tgz | basename }}

- name: "{{ app_name }}-install"
  shell: cd {{ tmp_path }}/{{ installer_dirname }} && make install PREFIX={{ prefix }}

- name: "{{ app_name }}-postinst_clean_untar_dir"
  file: path={{ tmp_path }}/{{ installer_dirname }} state=absent

# Config 
- name: "{{ app_name }}-conf_app_dirs"
  file: path={{ item }} state=directory owner=www-data group=www-data  recurse=yes
  with_items:
    - "{{ app_env }}"
    - "{{ app_assets }}"
    - "{{ app_uploads }}"
    - "{{ app_log }}"
    - "{{ app_fixtures }}"

- name: "{{ app_name }}-conf_config_file"
  template: src=config.ini dest={{ app_home }}/config.ini owner=www-data group=www-data

- name: "{{ app_name }}-conf_makefile"
  template: src=Makefile dest={{ app_home }}/Makefile owner=www-data group=www-data

- name: "{{ app_name }}-conf_fixtures_upload"
  copy: src={{ item }} dest={{ app_fixtures }} owner=www-data group=www-data
  with_items:
    - "initial_data_auth.yaml"

- name: "{{ app_name }}-conf_fixtures_install"
  shell: cd {{ app_home }} && make all
  when: with_fixtures == '1'

- name: "{{ app_name }}-conf_gunicorn"
  template: src=start_gunicorn.sh dest={{ app_home }}/start_gunicorn.sh mode=0751 owner=www-data group=www-data

- name: "{{ app_name }}-conf_perms"
  shell: chown -R www-data:www-data {{ app_home }}

